name: Build PR
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -e

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  authorize:
    runs-on: ubuntu-latest
    steps:
      - name: "Read authorizers1"
        id: authorizers
        run: |
          git clone \
          --depth 1  \
          --filter=blob:none  \
          --sparse \
          https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel;
          
          cd cos-fleet-catalog-camel
          git sparse-checkout set .github
          
          content=$(yq e -o=j -I=0 '.authorized[]' .github/authorized.yaml)
          
          echo "::set-output name=authorized::$content"
      - name: "Add label if authorized"
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{contains(steps.set_var.outputs.authorized, github.actor)}}
        with:
          labels: authorized

  build:
    if: contains( github.event.pull_request.labels.*.name, 'authorized')
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache m2 repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Build"
        run: |
          ./mvnw ${MAVEN_ARGS} clean install
      - name: "Tar Maven Repo"
        shell: bash
        run: |
          tar -czf ${{ runner.temp }}/maven-repo.tgz -C ~ .m2/repository
          ls -lh ${{ runner.temp }}/maven-repo.tgz
          df -h /
      - name: "Persist Maven Repo"
        uses: actions/upload-artifact@v2
        with:
          name: maven-repo-${{ github.run_id }}
          path: ${{ runner.temp }}/maven-repo.tgz
          retention-days: 1

  aws:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-aws,:cos-fleet-catalog-connectors-aws-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  azure:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-azure,:cos-fleet-catalog-connectors-azure-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  gcp:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-gcp,:cos-fleet-catalog-connectors-gcp-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  itops:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-itops,:cos-fleet-catalog-connectors-itops-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  messaging:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-messaging,:cos-fleet-catalog-connectors-messaging-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  misc:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-misc,:cos-fleet-catalog-connectors-misc-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  nosql:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-nosql,:cos-fleet-catalog-connectors-nosql-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  saas:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-saas,:cos-fleet-catalog-connectors-saas-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  social:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-social,:cos-fleet-catalog-connectors-social-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  sql:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-sql,:cos-fleet-catalog-connectors-sql-it"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}

  storage:
    needs:
      - build
    uses: ./.github/workflows/build-it.yaml
    secrets: inherit
    with:
      modules: ":cos-fleet-catalog-connectors-storage"
      containerRepo: ttl.sh
      containerOrg: ${{ github.sha }}
      containerTag: ${{ github.run_id }}-${{ github.run_attempt }}
